{"id": "CVE-2021-38561", "package": "pkg:golang/golang.org/x/text@v0.3.3-0.20200430171850-afb9336c4530", "purl": "pkg:golang/golang.org/x/text@v0.3.3-0.20200430171850-afb9336c4530", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.3.3-0.20200430171850-afb9336c4530", "fix_version": "0.3.7", "severity": "LOW", "cvss_score": "2.0", "short_description": "# Summary\nDue to improper index calculation, an incorrectly formatted language tag can cause Parse to panic via an out of bounds read. If Parse is used to process untrusted user inputs, this may be used as a vector for a denial of service attack.\n\n            ", "related_urls": ["https://go.dev/cl/340830", "https://go.googlesource.com/text/+/383b2e75a7a4198c42f8f87833eefb772868a56f"]}
{"id": "CVE-2021-33194", "package": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "purl": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.0.0-20210428183841-261fb518b1ed", "fix_version": "0.0.0-20210520170846-37e1c6afe023", "severity": "LOW", "cvss_score": "2.0", "short_description": "# Summary\nAn attacker can craft an input to ParseFragment that causes it to enter an infinite loop and never return.\n\n            ", "related_urls": ["https://go.dev/cl/311090", "https://go.googlesource.com/net/+/37e1c6afe02340126705deced573a85ab75209d7", "https://go.dev/issue/46288", "https://groups.google.com/g/golang-announce/c/wPunbCPkWUg"]}
{"id": "CVE-2021-44716", "package": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "purl": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.0.0-20210428183841-261fb518b1ed", "fix_version": "0.0.0-20211209124913-491a49abca63", "severity": "LOW", "cvss_score": "3.7", "short_description": "# Summary\nAn attacker can cause unbounded memory growth in servers accepting HTTP/2 requests.\n\n            ", "related_urls": ["https://go.dev/cl/369794", "https://go.dev/issue/50058", "https://groups.google.com/g/golang-announce/c/hcmEScgc00k"]}
{"id": "CVE-2022-27664", "package": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "purl": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.0.0-20210428183841-261fb518b1ed", "fix_version": "0.0.0-20220906165146-f3363e06e74c", "severity": "LOW", "cvss_score": "3.7", "short_description": "# Summary\nHTTP/2 server connections can hang forever waiting for a clean shutdown that was preempted by a fatal error. This condition can be exploited by a malicious client to cause a denial of service.\n\n            ", "related_urls": ["https://groups.google.com/g/golang-announce/c/x49AQzIVX-s", "https://go.dev/issue/54658", "https://go.dev/cl/428735"]}
{"id": "CVE-2022-32149", "package": "pkg:golang/golang.org/x/text@v0.3.3-0.20200430171850-afb9336c4530", "purl": "pkg:golang/golang.org/x/text@v0.3.3-0.20200430171850-afb9336c4530", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.3.3-0.20200430171850-afb9336c4530", "fix_version": "0.3.8", "severity": "LOW", "cvss_score": "2.0", "short_description": "# Summary\nAn attacker may cause a denial of service by crafting an Accept-Language header which ParseAcceptLanguage will take significant time to parse.\n\n## Related CVE(s)\nCVE-2022-32149, GHSA-69ch-w2m2-3vjp\n            \n            ", "related_urls": ["https://go.dev/issue/56152", "https://go.dev/cl/442235", "https://groups.google.com/g/golang-announce/c/-hjNw559_tE/m/KlGTfid5CAAJ"]}
{"id": "CVE-2022-41717", "package": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "purl": "pkg:golang/golang.org/x/net@v0.0.0-20210428183841-261fb518b1ed", "package_type": "golang.org/x", "package_usage": "N/A", "version": "v0.0.0-20210428183841-261fb518b1ed", "fix_version": "0.4.0", "severity": "LOW", "cvss_score": "3.7", "short_description": "# Summary\nAn attacker can cause excessive memory growth in a Go server accepting HTTP/2 requests.\n\nHTTP/2 server connections contain a cache of HTTP header keys sent by the client. While the total number of entries in this cache is capped, an attacker sending very large keys can cause the server to allocate approximately 64 MiB per open connection.\n\n            ", "related_urls": ["https://go.dev/issue/56350", "https://go.dev/cl/455717", "https://go.dev/cl/455635", "https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU/m/yZDrXjIiBQAJ"]}
{"id": "CVE-2022-0391", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "3.6.14", "severity": "HIGH", "cvss_score": "7.5", "short_description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.", "related_urls": ["https://bugs.python.org/issue43882", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/", "https://security.netapp.com/advisory/ntap-20220225-0009/", "https://www.oracle.com/security-alerts/cpuapr2022.html"]}
{"id": "CVE-2022-26488", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "HIGH", "cvss_score": "7.0", "short_description": "In Python before 3.10.3 on Windows, local users can gain privileges because the search path is inadequately secured. The installer may allow a local attacker to add user-writable directories to the system search path. To exploit, an administrator must have installed Python for all users and enabled PATH entries. A non-administrative user can trigger a repair that incorrectly adds user-writable paths into PATH, enabling search-path hijacking of other users and system services. This affects Python (CPython) through 3.7.12, 3.8.x through 3.8.12, 3.9.x through 3.9.10, and 3.10.x through 3.10.2.", "related_urls": ["https://mail.python.org/archives/list/security-announce@python.org/thread/657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN/", "https://security.netapp.com/advisory/ntap-20220419-0005/"]}
{"id": "CVE-2022-45061", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.", "related_urls": ["https://github.com/python/cpython/issues/98433", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O67LRHDTJWH544KXB6KY4HMHQLYDXFPK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4WBZJNSALFGMPYTINIF57HAAK46U72WQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GTPVDZDATRQFE6KAT6B4BQIQ4GRHIIIJ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RTN2OOLKYTG34DODUEJGT5MLC2PFGPBA/", "https://security.netapp.com/advisory/ntap-20221209-0007/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZB5YCMIRVX35RUB6XPOWKENCVCJEVDRK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PLQ2BNZVBBAQPV3SPRU24ZD37UYJJS7W/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VCMDX6IFKLOA3NXUQEV524L5LHTPI2JI/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORVCQGJCCAVLN4DJDTWGREFCUWXKQRML/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3D5TX4TDJPXHXD2QICKTY3OCQC3JARP/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/63FS6VHY4DCS74HBTEINUDOECQ2X6ZCH/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCDJXNBHWXNYUTOEV4H2HCFSRKV3SYL3/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RH57BNT4VQERGEJ5SXNXSVMDYP66YD4H/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YPNWZKXPKTNHS5FVMN7UQZ2UPCSEFJUK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LKWAMPURWUV3DCCT4J7VHRF4NT2CFVBR/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/35YDIWCUMWTMDBWFRAVENFH6BLB65D6S/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B3YI6JYARWU6GULWOHNUROSACT54XFFS/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JTYVESWVBPD57ZJC35G5722Q6TS37WSB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KNE4GMD45RGC2HWUAAIGTDHT5VJ2E4O4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UHVW73QZJMHA4MK7JBT7CXX7XSNYQEGF/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2AOUKI72ACV6CHY2QUFO6VK2DNMVJ2MB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/X3EJ6J7PXVQOULBQZQGBXCXY6LFF6LZD/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXZJL3CNAFS5PAIR7K4RL62S3Y7THR7O/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QLUGZSEAO3MBWGKCUSMKQIRYJZKJCIOB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IN26PWZTYG6IF3APLRXQJBVACQHZUPT2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDK3ZZBRYFO47ET3N4BNTKVXN47U6ICY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WQPHKGNXUJC3TC3BDW5RKGROWRJVSFR/"]}
{"id": "CVE-2021-23336", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "3.6.13", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "The package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.", "related_urls": ["https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933", "https://github.com/python/cpython/pull/24297", "https://snyk.io/blog/cache-poisoning-in-popular-open-source-packages/", "http://www.openwall.com/lists/oss-security/2021/02/19/4", "https://lists.debian.org/debian-lts-announce/2021/02/msg00030.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCQTCSP6SCVIYNIRUJC5X7YBVUHPLSC4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NODWHDIFBQE5RU5PUWUVE47JOT5VCMJ2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MNUN5SOMFL2BBKP6ZAICIIUPQKZDMGYO/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MP572OLHMS7MZO4KUPSCIMSZIA5IZZ62/", "https://lists.apache.org/thread.html/rf9fa47ab66495c78bb4120b0754dd9531ca2ff0430f6685ac9b07772@%3Cdev.mina.apache.org%3E", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FONHJIOZOFD7CD35KZL6SVBUTMBPGZGA/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KJXCMHLY7H3FIYLE4OKDYUILU2CCRUCZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3YKKDLXL3UEZ3J426C2XTBS63AHE46SM/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TFTELUMWZE3KV3JB2H5EE6VFRZFRD5MV/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OAGSWNGZJ6HQ5ISA67SNMK3CJRKICET7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NJSCSN722JO2E2AGPWD4NTGVELVRPB4R/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HZTM7KLHFCE3LWSEVO2NAFLUHMGYMCRY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3EPYWWFDV22CJ5AOH5VCE72DOASZZ255/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IHQDU7NXA7EWAE4W7VO6MURVJIULEPPR/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LVNH6Z24IG3E67ZCQGGJ46FZB4XFLQNZ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W2LSKBEFI5SYEY5FM6ICZVZM5WRQUCS4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46N6A52EGSXHJYCZWVMBJJIH4NWIV2B5/", "https://security.netapp.com/advisory/ntap-20210326-0004/", "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html", "https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/", "https://security.gentoo.org/glsa/202104-04", "https://lists.apache.org/thread.html/ra8ce70088ba291f358e077cafdb14d174b7a1ce9a9d86d1b332d6367@%3Cusers.airflow.apache.org%3E", "http://www.openwall.com/lists/oss-security/2021/05/01/2", "https://lists.apache.org/thread.html/rc005f4de9d9b0ba943ceb8ff5a21a5c6ff8a9df52632476698d99432@%3Cannounce.apache.org%3E", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGIY6I4YS3WOXAK4SXKIEOC2G4VZKIR7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RSLQD5CCM75IZGAMBDGUZEATYU5YSGJ7/", "https://www.oracle.com/security-alerts/cpuApr2021.html", "https://www.oracle.com//security-alerts/cpujul2021.html", "https://www.oracle.com/security-alerts/cpuoct2021.html", "https://www.oracle.com/security-alerts/cpujan2022.html"]}
{"id": "CVE-2021-3426", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.18", "severity": "MEDIUM", "cvss_score": "5.7", "short_description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.", "related_urls": ["https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/", "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/", "https://bugzilla.redhat.com/show_bug.cgi?id=1935913", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/", "https://security.gentoo.org/glsa/202104-04", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/", "https://security.netapp.com/advisory/ntap-20210629-0003/", "https://www.oracle.com/security-alerts/cpuoct2021.html", "https://www.oracle.com/security-alerts/cpujan2022.html"]}
{"id": "CVE-2021-3733", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "3.6.14", "severity": "MEDIUM", "cvss_score": "6.5", "short_description": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.", "related_urls": ["https://github.com/python/cpython/commit/7215d1ae25525c92b026166f9d5cac85fb", "https://ubuntu.com/security/CVE-2021-3733", "https://bugs.python.org/issue43075", "https://bugzilla.redhat.com/show_bug.cgi?id=1995234", "https://github.com/python/cpython/pull/24391", "https://security.netapp.com/advisory/ntap-20220407-0001/"]}
{"id": "CVE-2020-8492", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.5", "short_description": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.", "related_urls": ["https://github.com/python/cpython/pull/18284", "https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html", "https://bugs.python.org/issue39503", "https://security.netapp.com/advisory/ntap-20200221-0001/", "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html", "https://usn.ubuntu.com/4333-1/", "https://usn.ubuntu.com/4333-2/", "https://security.gentoo.org/glsa/202005-09", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/rdb31a608dd6758c6093fd645aea3fbf022dd25b37109b6aaea5bc0b5@%3Ccommits.cassandra.apache.org%3E", "https://lists.apache.org/thread.html/rfec113c733162b39633fd86a2d0f34bf42ac35f711b3ec1835c774da@%3Ccommits.cassandra.apache.org%3E"]}
{"id": "CVE-2019-10160", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "A security regression of CVE-2019-9636 was discovered in python since commit d537ab0ff9767ef024f26246899728f0116b1ec3 affecting versions 2.7, 3.5, 3.6, 3.7 and from v3.8.0a4 through v3.8.0b1, which still allows an attacker to exploit CVE-2019-9636 by abusing the user and password parts of a URL. When an application parses user-supplied URLs to store cookies, authentication credentials, or other kind of information, it is possible for an attacker to provide specially crafted URLs to make the application locate host-related information (e.g. cookies, authentication data) and send them to a different host than where it should, unlike if the URLs had been correctly parsed. The result of an attack may vary based on the application.", "related_urls": ["https://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization2.html", "https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e", "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10160", "https://github.com/python/cpython/commit/fd1771dbdd28709716bd531580c40ae5ed814468", "https://github.com/python/cpython/commit/f61599b050c621386a3fc6bc480359e2d3bb93de", "https://github.com/python/cpython/commit/250b62acc59921d399f0db47db3b462cd6037e09", "https://security.netapp.com/advisory/ntap-20190617-0003/", "https://access.redhat.com/errata/RHSA-2019:1587", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://access.redhat.com/errata/RHSA-2019:1700", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/", "https://access.redhat.com/errata/RHSA-2019:2437", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00042.html", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NF3DRDGMVIRYNZMSLJIHNW47HOUQYXVG/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2019-15903", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "HIGH", "cvss_score": "7.5", "short_description": "In libexpat before 2.2.8, crafted XML input could fool the parser into changing from DTD parsing to document parsing too early; a consecutive call to XML_GetCurrentLineNumber (or XML_GetCurrentColumnNumber) then resulted in a heap-based buffer over-read.", "related_urls": ["https://github.com/libexpat/libexpat/pull/318", "https://github.com/libexpat/libexpat/commit/c20b758c332d9a13afbbb276d30db1d183a85d43", "https://github.com/libexpat/libexpat/issues/317", "https://usn.ubuntu.com/4132-1/", "https://github.com/libexpat/libexpat/issues/342", "https://seclists.org/bugtraq/2019/Sep/30", "http://packetstormsecurity.com/files/154503/Slackware-Security-Advisory-expat-Updates.html", "https://usn.ubuntu.com/4132-2/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BDUTI5TVQWIGGQXPEVI4T2ENHFSBMIBP/", "https://www.debian.org/security/2019/dsa-4530", "https://seclists.org/bugtraq/2019/Sep/37", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A4TZKPJFTURRLXIGLB34WVKQ5HGY6JJA/", "https://security.netapp.com/advisory/ntap-20190926-0004/", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00081.html", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00080.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/S26LGXXQ7YF2BP3RGOWELBFKM6BHF6UG/", "https://seclists.org/bugtraq/2019/Oct/29", "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html", "http://packetstormsecurity.com/files/154947/Slackware-Security-Advisory-mozilla-firefox-Updates.html", "https://usn.ubuntu.com/4165-1/", "https://www.debian.org/security/2019/dsa-4549", "https://access.redhat.com/errata/RHSA-2019:3237", "https://access.redhat.com/errata/RHSA-2019:3210", "https://seclists.org/bugtraq/2019/Nov/1", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00000.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00002.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00003.html", "https://access.redhat.com/errata/RHSA-2019:3756", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00013.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00017.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00019.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00016.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00018.html", "https://lists.debian.org/debian-lts-announce/2019/11/msg00006.html", "https://seclists.org/bugtraq/2019/Nov/24", "https://www.debian.org/security/2019/dsa-4571", "https://lists.debian.org/debian-lts-announce/2019/11/msg00017.html", "https://security.gentoo.org/glsa/201911-08", "https://usn.ubuntu.com/4202-1/", "https://support.apple.com/kb/HT210788", "https://support.apple.com/kb/HT210785", "https://support.apple.com/kb/HT210790", "https://support.apple.com/kb/HT210789", "https://seclists.org/bugtraq/2019/Dec/21", "https://seclists.org/bugtraq/2019/Dec/23", "https://seclists.org/bugtraq/2019/Dec/17", "https://support.apple.com/kb/HT210793", "https://support.apple.com/kb/HT210795", "https://support.apple.com/kb/HT210794", "http://seclists.org/fulldisclosure/2019/Dec/23", "http://seclists.org/fulldisclosure/2019/Dec/26", "http://seclists.org/fulldisclosure/2019/Dec/27", "http://seclists.org/fulldisclosure/2019/Dec/30", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00008.html", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://www.oracle.com/security-alerts/cpuapr2020.html", "https://usn.ubuntu.com/4335-1/", "https://www.oracle.com/security-alerts/cpuoct2020.html", "https://www.tenable.com/security/tns-2021-11"]}
{"id": "CVE-2019-16056", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.", "related_urls": ["https://bugs.python.org/issue34155", "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K4KZEFP6E4YPYB52AF4WXCUDSGQOTF37/", "https://lists.debian.org/debian-lts-announce/2019/09/msg00019.html", "https://lists.debian.org/debian-lts-announce/2019/09/msg00018.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NF3DRDGMVIRYNZMSLJIHNW47HOUQYXVG/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "https://security.netapp.com/advisory/ntap-20190926-0005/", "https://usn.ubuntu.com/4151-1/", "https://usn.ubuntu.com/4151-2/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QP46PQSUKYPGWTADQ67NOV3BUN6JM34Z/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QASRD4E2G65GGEHYKVHYCXB2XWAGTNL4/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SDQQ56P7ZZR64XV5DUVWNSNXKKEXUG2J/", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00012.html", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00021.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://access.redhat.com/errata/RHSA-2019:3948", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BEARDOTXCYPYELKBD2KWZ27GSPXDI3GQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OYGESQSGIHDCIGOBVF7VXCMIE6YDWRYB/", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://www.oracle.com/security-alerts/cpuapr2020.html", "https://www.oracle.com/security-alerts/cpujul2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2019-16935", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.", "related_urls": ["https://bugs.python.org/issue38243", "https://github.com/python/cpython/blob/e007860b8b3609ce0bc62b1780efaa06241520bd/Lib/DocXMLRPCServer.py#L213", "https://github.com/python/cpython/blob/35c0809158be7feae4c4f877a08b93baea2d8291/Lib/xmlrpc/server.py#L897", "https://github.com/python/cpython/pull/16373", "https://usn.ubuntu.com/4151-1/", "https://usn.ubuntu.com/4151-2/", "https://security.netapp.com/advisory/ntap-20191017-0004/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00012.html", "http://lists.opensuse.org/opensuse-security-announce/2019-11/msg00021.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BEARDOTXCYPYELKBD2KWZ27GSPXDI3GQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OYGESQSGIHDCIGOBVF7VXCMIE6YDWRYB/", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://www.oracle.com/security-alerts/cpujul2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2021/04/msg00015.html"]}
{"id": "CVE-2019-18348", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.). This is fixed in: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1.", "related_urls": ["https://bugs.python.org/issue30458#msg347282", "https://bugzilla.redhat.com/show_bug.cgi?id=1727276", "https://security.netapp.com/advisory/ntap-20191107-0004/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://usn.ubuntu.com/4333-1/", "https://usn.ubuntu.com/4333-2/", "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://www.oracle.com/security-alerts/cpuoct2020.html"]}
{"id": "CVE-2019-3902", "package": "pkg:pypi/mercurial@4.8.2", "purl": "pkg:pypi/mercurial@4.8.2", "package_type": "mercurial", "package_usage": "N/A", "version": "4.8.2", "fix_version": "4.9", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "A flaw was found in Mercurial before 4.9. It was possible to use symlinks and subrepositories to defeat Mercurial's path-checking logic and write files outside a repository.", "related_urls": ["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3902", "https://lists.debian.org/debian-lts-announce/2019/04/msg00024.html", "https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.9_.282019-02-01.29", "https://usn.ubuntu.com/4086-1/", "https://lists.debian.org/debian-lts-announce/2020/07/msg00032.html"]}
{"id": "CVE-2019-9636", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.7, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.3, v3.7.3rc1, v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html", "https://github.com/python/cpython/pull/12201", "https://bugs.python.org/issue36216", "http://www.securityfocus.com/bid/107400", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/L25RTMKCF62DLC2XVSNXGX7C7HXISLVM/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/D3LXPABKVLFYUHRYJPM3CSS5MS6FXKS7/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICBEGRHIPHWPG2VGYS6R4EVKVUUF4AQW/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TR6GCO3WTV4D5L23WTCBF275VE6BVNI3/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CFBAAGM27H73OLYBUA2IAZFSUN6KGLME/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFAXBEY2TGOBDRKTR556JBXBVFSAKD6I/", "https://access.redhat.com/errata/RHSA-2019:0710", "https://access.redhat.com/errata/RHSA-2019:0765", "https://access.redhat.com/errata/RHSA-2019:0806", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00097.html", "https://access.redhat.com/errata/RHSA-2019:0902", "https://access.redhat.com/errata/RHSA-2019:0997", "https://access.redhat.com/errata/RHSA-2019:0981", "https://access.redhat.com/errata/RHBA-2019:0959", "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00024.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://security.netapp.com/advisory/ntap-20190517-0001/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://access.redhat.com/errata/RHSA-2019:1467", "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://access.redhat.com/errata/RHBA-2019:0763", "https://access.redhat.com/errata/RHBA-2019:0764", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00042.html", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "https://access.redhat.com/errata/RHSA-2019:2980", "https://access.redhat.com/errata/RHSA-2019:3170", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://www.oracle.com/security-alerts/cpujan2020.html", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "https://www.oracle.com/security-alerts/cpujul2022.html"]}
{"id": "CVE-2019-9674", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb.", "related_urls": ["https://github.com/python/cpython/blob/master/Lib/zipfile.py", "https://bugs.python.org/issue36462", "https://www.python.org/news/security/", "https://bugs.python.org/issue36260", "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb", "https://security.netapp.com/advisory/ntap-20200221-0003/", "http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html", "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html", "https://usn.ubuntu.com/4428-1/"]}
{"id": "CVE-2019-9740", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://bugs.python.org/issue36276", "http://www.securityfocus.com/bid/107466", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://access.redhat.com/errata/RHSA-2019:1260", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://security.netapp.com/advisory/ntap-20190619-0005/", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html", "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html", "https://usn.ubuntu.com/4127-1/", "https://seclists.org/bugtraq/2019/Oct/29", "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://access.redhat.com/errata/RHSA-2019:3725", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "http://www.openwall.com/lists/oss-security/2021/02/04/2", "https://www.oracle.com/security-alerts/cpujul2022.html"]}
{"id": "CVE-2019-9947", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "MEDIUM", "cvss_score": "6.1", "short_description": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.", "related_urls": ["https://bugs.python.org/issue35906", "https://security.netapp.com/advisory/ntap-20190404-0004/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "https://access.redhat.com/errata/RHSA-2019:1260", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html", "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://access.redhat.com/errata/RHSA-2019:3725", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html", "http://www.openwall.com/lists/oss-security/2021/02/04/2"]}
{"id": "CVE-2019-9948", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": "2.7.17", "severity": "CRITICAL", "cvss_score": "9.1", "short_description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.", "related_urls": ["https://github.com/python/cpython/pull/11842", "https://bugs.python.org/issue35907", "http://www.securityfocus.com/bid/107549", "https://security.netapp.com/advisory/ntap-20190404-0004/", "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html", "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html", "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "https://access.redhat.com/errata/RHSA-2019:1700", "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/", "https://access.redhat.com/errata/RHSA-2019:2030", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://seclists.org/bugtraq/2019/Oct/29", "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html", "https://access.redhat.com/errata/RHSA-2019:3335", "https://access.redhat.com/errata/RHSA-2019:3520", "https://security.gentoo.org/glsa/202003-26", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
{"id": "CVE-2018-20852", "package": "pkg:pypi/python@2.7.16", "purl": "pkg:pypi/python@2.7.16", "package_type": "python", "package_usage": "N/A", "version": "2.7.16", "fix_version": null, "severity": "MEDIUM", "cvss_score": "5.3", "short_description": "http.cookiejar.DefaultPolicy.domain_return_ok in Lib/http/cookiejar.py in Python before 3.7.3 does not correctly validate the domain: it can be tricked into sending existing cookies to the wrong server. An attacker may abuse this flaw by using a server with a hostname that has another valid hostname as a suffix (e.g., pythonicexample.com to steal cookies for example.com). When a program uses http.cookiejar.DefaultPolicy and tries to do an HTTP connection to an attacker-controlled server, existing cookies can be leaked to the attacker. This affects 2.x through 2.7.16, 3.x before 3.4.10, 3.5.x before 3.5.7, 3.6.x before 3.6.9, and 3.7.x before 3.7.3.", "related_urls": ["https://bugs.python.org/issue35121", "https://python-security.readthedocs.io/vuln/cookie-domain-check.html", "https://lists.debian.org/debian-lts-announce/2019/08/msg00022.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00071.html", "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00074.html", "https://lists.debian.org/debian-lts-announce/2019/08/msg00040.html", "https://usn.ubuntu.com/4127-2/", "https://usn.ubuntu.com/4127-1/", "https://access.redhat.com/errata/RHSA-2019:3725", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/", "https://access.redhat.com/errata/RHSA-2019:3948", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "https://security.gentoo.org/glsa/202003-26", "https://www.oracle.com/security-alerts/cpuapr2020.html", "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html", "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"]}
